const projects = [
    {
        key: 1,
        title: 'Yelp-Alytics',
        description: 'Yelp-Alytics is a service-oriented app measuring the effectiveness of personalized restaurant recommendations. User behavior (clicks, checkins and reviews) is recorded and analyzed after users are served either generic or personalized list of restaurants.',
        picture: './static/yelpalytics.jpg',
        techstack: ['Node', 'ElasticSearch', 'Kibana', 'MySQL', 'AWS'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
    {
        key: 2,
        title: 'Q-Deux',
        description: 'Q-Deux is an app built for restaurant owners to manage customer wait queues. Restaurant managers sign up and add their restaurants to the app. Customers add themselves to restaurant queues and are notified by text/e-mail when their table is ready.',
        picture: './static/qdeux.jpg',
        techstack: ['React', 'Node/Express', 'PostgreSQL'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
    {
        key: 3,
        title: 'Travel With Friends',
        description: 'Travel With Friends is a social trip planning app to manage logistics between groups of travellers. Features include shared expense tracking and voting on landmarks.',
        picture: './static/travelfriends.jpg',
        techstack: ['React/Redux', 'Node/Express', 'MySQL'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
    {
        key: 4,
        title: 'Personal Homepage',
        description: 'Personal landing page to display portfolio of apps and projects. Project cards are rendered dynamically and individual projects are easily added and removed.',
        picture: './static/template.jpeg',
        techstack: ['React', 'Node/Express', 'AWS'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
    {
        key: 5,
        title: 'ORCATECH App',
        description: 'Inventory management app to track equipment within an office. This was a solo project used to demonstrate proficiency in React and PHP',
        picture: './static/orcatech.jpg',
        techstack: ['React', 'PHP', 'MySQL'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
    {
        key: 6,
        title: 'Buffer Inventory Manager',
        description: 'Scientific buffer inventory management app used by scientists to save buffer recipes as well as provide MSDS (Material Safety Data Sheet) of buffer components. ',
        picture: './static/bufferapp.jpg',
        techstack: ['AngularJS', 'Node/Express', 'MongoDB'],
        gitHub: 'http://github.com/ddai85',
        video: 'http://youtube.com',
    },
]

module.exports = projects;